[package]
name = "protocols"
version = "0.1.0"
edition = "2024"


[dependencies]
domain = { path = "../domain" }
anyhow = "1.0.99"
chrono = { version = "0.4.41", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
async-trait = "0.1.89"
