[package]
name = "main"
version = "0.1.0"
edition = "2024"

[dependencies]
presentation = { path = "../presentation" }
axum = "0.8.4"
tokio = { version = "1.47.1", features = ["full"] }
futures = "0.3.31"
serde = { version = "1.0.220", features = ["derive"] }
serde_json = "1.0.143"
